spring:
  application:
    name: Test-1
  datasource:
    url: jdbc:postgresql://localhost:5432/test1
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
      path: /api-docs
  swagger-ui:
      path: /swagger-ui.html
      operations-sorter: method
      tags-sorter: alpha
      try-it-out-enabled: true

scheduled:
  rate:
      cron: "* * * * * *"
      enabled: true

feign:
  client:
      config:
          ef2:
              max-attempts: 5
              period: 200
              retryer: feign.Retryer.Default

management:
  endpoint:
      web:
          exposure:
              include: ""
      health:
          show-details: always